from polyjit.buildbot.builders import benchbuild
#from polyjit.buildbot.builders import slurm
#from polyjit.buildbot.builders import llvm
from polyjit.buildbot.builders import superbuild
from polyjit.buildbot.builders import vara_master_dev
from polyjit.buildbot.builders import vara_master_opt
from polyjit.buildbot.builders import vara_feature_dev
from polyjit.buildbot.builders import vara_feature_opt
from polyjit.buildbot.builders import vara_phasar_master_dev
